export const ActivityType = {
    // Task
    EXTERNAL_TASK: "EXTERNAL_TASK",
    RECEIVE_TASK: "RECEIVE_TASK",

    // Gateway
    PARALLEL_GATEWAY: "PARALLEL_GATEWAY",
    INCLUSIVE_GATEWAY: "INCLUSIVE_GATEWAY",
    EXCLUSIVE_GATEWAY: "EXCLUSIVE_GATEWAY",
    EVENT_BASED_GATEWAY: "EVENT_BASED_GATEWAY",

    // Events
    START_EVENT: "START_EVENT",
    MESSAGE_START_EVENT: "MESSAGE_START_EVENT",
    END_EVENT: "END_EVENT",
    INTERMEDIATE_CATCH_EVENT: "INTERMEDIATE_CATCH_EVENT",
    MESSAGE_INTERMEDIATE_CATCH_EVENT: "MESSAGE_INTERMEDIATE_CATCH_EVENT",
    ERROR_END_EVENT: "ERROR_END_EVENT",
    ERROR_START_EVENT: "ERROR_START_EVENT",
    TERMINATE_END_EVENT: "TERMINATE_END_EVENT",

    // SubProcess
    SUBPROCESS: "SUBPROCESS",
    EVENT_SUBPROCESS: "EVENT_SUBPROCESS",
    CALL_ACTIVITY: "CALL_ACTIVITY",
} as const;

export type ActivityType = typeof ActivityType[keyof typeof ActivityType];
